services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    name: postgres17_data
